### ISSUE TITLE
ModuleNotFoundError: No module named 'omni.isaac.sensor'

### ISSUE THREAD

**Issue by jiaming-robot-learning** [StanfordVL/OmniGibson#113]
Hi,

I tried to install Omnigibson using the source code following the instructions. After it is installed I run

> python -m omnigibson.examples.object_states.clearning_demo.py

and got the following error message. (actually it gives the same error when I run any examples..

```
...
3.955s] [ext: omni.graph.window.generic-1.3.8] startup
[3.956s] [ext: omni.isaac.utils-0.1.11] startup
[3.959s] [ext: omni.kit.property.audio-1.0.5] startup
[3.960s] [ext: omni.kit.property.skel-1.0.1] startup
[3.961s] [ext: omni.kit.property.render-1.1.0] startup
[3.962s] [ext: omni.kit.property.camera-1.0.3] startup
[3.962s] [ext: omni.kit.property.geometry-1.2.0] startup
[3.964s] [ext: omni.kit.property.light-1.0.5] startup
[3.965s] [ext: omni.kit.property.transform-1.0.2] startup
[3.967s] [ext: omni.isaac.universal_robots-0.3.0] startup
[3.967s] [ext: omni.isaac.occupancy_map-0.2.4] startup
[3.977s] [ext: omni.kit.window.console-0.2.0] startup
[3.981s] [ext: omni.kit.window.status_bar-0.1.1] startup
[3.984s] [ext: omni.kit.property.bundle-1.2.4] startup
[3.985s] [ext: omni.kit.menu.file-1.0.8] startup
[3.986s] [ext: omni.kit.manipulator.viewport-1.0.6] startup
[3.988s] [ext: omni.isaac.urdf-0.4.0] startup
[4.008s] [ext: omni.isaac.dofbot-0.3.0] startup
[4.009s] [ext: omni.kit.window.title-1.1.2] startup
[4.010s] [ext: omni.kit.profiler.window-1.4.4] startup
[4.014s] [ext: omni.graph.visualization.nodes-1.1.1] startup
[4.016s] [ext: omni.isaac.synthetic_utils-0.3.5] startup
[4.018s] [ext: semantics.schema.editor-0.2.3] startup
[4.020s] [ext: omni.isaac.sim.python-2022.1.1] startup
[4.021s] Simulation App Starting
[4.491s] app ready
[6.087s] Simulation App Startup Complete
WARNING:root:Requested average specs of the object categories in the OmniGibson Dataset of objects, but the file cannot be found. Did you download the dataset? Returning an empty dictionary
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/omnigibson/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/user/anaconda3/envs/omnigibson/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/data/omniverse/lib/isaac_sim-2022.1.1/OmniGibson/omnigibson/__init__.py", line 144, in <module>
    REGISTERED_TASKS, ALL_SENSOR_MODALITIES = start()
  File "/data/omniverse/lib/isaac_sim-2022.1.1/OmniGibson/omnigibson/__init__.py", line 127, in start
    sim = create_sim()
  File "/data/omniverse/lib/isaac_sim-2022.1.1/OmniGibson/omnigibson/__init__.py", line 116, in create_sim
    from omnigibson.simulator import Simulator
  File "/data/omniverse/lib/isaac_sim-2022.1.1/OmniGibson/omnigibson/simulator.py", line 29, in <module>
    from omnigibson.scenes import Scene
  File "/data/omniverse/lib/isaac_sim-2022.1.1/OmniGibson/omnigibson/scenes/__init__.py", line 1, in <module>
    from omnigibson.scenes.scene_base import Scene, REGISTERED_SCENES
  File "/data/omniverse/lib/isaac_sim-2022.1.1/OmniGibson/omnigibson/scenes/scene_base.py", line 7, in <module>
    from omnigibson.prims.xform_prim import XFormPrim
  File "/data/omniverse/lib/isaac_sim-2022.1.1/OmniGibson/omnigibson/prims/__init__.py", line 3, in <module>
    from omnigibson.prims.entity_prim import EntityPrim
  File "/data/omniverse/lib/isaac_sim-2022.1.1/OmniGibson/omnigibson/prims/entity_prim.py", line 16, in <module>
    from omnigibson.prims.rigid_prim import RigidPrim
  File "/data/omniverse/lib/isaac_sim-2022.1.1/OmniGibson/omnigibson/prims/rigid_prim.py", line 16, in <module>
    from omni.isaac.sensor import _sensor as _s
ModuleNotFoundError: No module named 'omni.isaac.sensor'
Segmentation fault (core dumped)
```

**Comment by jiaming-robot-learning** [comment]
The issue is isaac sim needs to be updated.
