### ISSUE TITLE
pxr.Tf.ErrorException:  Error in 'pxrInternal_v0_20__pxrReserved__::UsdStage::_SetValueImpl'

### ISSUE THREAD

**Issue by jiaming-robot-learning** [StanfordVL/OmniGibson#123]
Hi, 

when running the robot_control_example,

> python -m omnigibson.examples.robots.robot_control_example

it reports the following error. It seems related to the object_state reset issue that I reported last week.

```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/omnigibson/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/omnigibson/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/examples/robots/robot_control_example.py", line 145, in <module>
    main()
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/examples/robots/robot_control_example.py", line 95, in main
    env = og.Environment(configs=cfg, action_timestep=1/60., physics_timestep=1/60.)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/utils/python_utils.py", line 89, in wrapper
    func(*values.args, **values.kwargs)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/envs/env_base.py", line 70, in __init__
    self.load()
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/envs/env_base.py", line 282, in load
    self.reset()
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/envs/env_base.py", line 397, in reset
    self.task.reset(self)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/tasks/task_base.py", line 163, in reset
    self._reset_agent(env)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/tasks/dummy_task.py", line 30, in _reset_agent
    land_object(robot, np.zeros(3), np.array([0, 0, 0, 1]), env.initial_pos_z_offset)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/utils/sim_utils.py", line 340, in land_object
    place_base_pose(obj, pos, quat, z_offset)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/utils/sim_utils.py", line 278, in place_base_pose
    lower, _ = obj.states[AABB].get_value()
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/object_states/object_state_base.py", line 241, in get_value
    self.update_cache(get_value_args=key)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/object_states/object_state_base.py", line 113, in update_cache
    val = self._get_value(*get_value_args)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/object_states/aabb.py", line 9, in _get_value
    aabb_low, aabb_hi = BoundingBoxAPI.compute_aabb(self.obj)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/utils/usd_utils.py", line 276, in compute_aabb
    return cls._compute_flatcache_aabb(prim=prim) if gm.ENABLE_FLATCACHE else \
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/utils/usd_utils.py", line 315, in _compute_flatcache_aabb
    FlatcacheAPI.sync_raw_object_transforms_in_usd(prim=obj)
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/utils/usd_utils.py", line 438, in sync_raw_object_transforms_in_usd
    joint.set_attribute(f"state:{state_name}:physics:position", float(joint_pos))
  File "/data/omniverse/lib/isaac_sim-2022.2.0/OmniGibson/omnigibson/prims/prim_base.py", line 251, in set_attribute
    self._prim.GetAttribute(attr).Set(val)
pxr.Tf.ErrorException: 
        Error in 'pxrInternal_v0_20__pxrReserved__::UsdStage::_SetValueImpl' at line 6028 in file /buildAgent/work/ca6c508eae419cf8/USD/pxr/usd/usd/stage.cpp : 'Empty typeName for </World/robot0/base_link/l_wheel_joint.state:angular:physics:position>'
Exception ignored in: <function _make_registry.<locals>._Registry.__del__ at 0x7fd1f0ef5b00>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 103, in __del__
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 98, in destroy
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _make_registry.<locals>._Registry.__del__ at 0x7fd1f0ef5b00>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 103, in __del__
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 98, in destroy
TypeError: 'NoneType' object is not callable
Exception ignored in: <function SettingChangeSubscription.__del__ at 0x7fd3ef754f80>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/kernel/py/omni/kit/app/_impl/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'get_settings'
Exception ignored in: <function SettingChangeSubscription.__del__ at 0x7fd3ef754f80>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/kernel/py/omni/kit/app/_impl/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'get_settings'
Exception ignored in: <function SettingChangeSubscription.__del__ at 0x7fd3ef754f80>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/kernel/py/omni/kit/app/_impl/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'get_settings'
Exception ignored in: <function SettingChangeSubscription.__del__ at 0x7fd3ef754f80>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/kernel/py/omni/kit/app/_impl/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'get_settings'
Exception ignored in: <function SettingChangeSubscription.__del__ at 0x7fd3ef754f80>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/kernel/py/omni/kit/app/_impl/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'get_settings'
Exception ignored in: <function SettingChangeSubscription.__del__ at 0x7fd3ef754f80>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/kernel/py/omni/kit/app/_impl/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'get_settings'
Exception ignored in: <function SettingChangeSubscription.__del__ at 0x7fd3ef754f80>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/kernel/py/omni/kit/app/_impl/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'get_settings'
Exception ignored in: <function _make_registry.<locals>._Registry.__del__ at 0x7fd1f0ef5710>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 103, in __del__
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 98, in destroy
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _make_registry.<locals>._Registry.__del__ at 0x7fd1f0ef5710>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 103, in __del__
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 98, in destroy
TypeError: 'NoneType' object is not callable
Exception ignored in: <function SettingChangeSubscription.__del__ at 0x7fd3ef754f80>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/kernel/py/omni/kit/app/_impl/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'get_settings'
Exception ignored in: <function Task.__del__ at 0x7fd3f0fd13b0>
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/omnigibson/lib/python3.7/asyncio/tasks.py", line 146, in __del__
AttributeError: 'NoneType' object has no attribute '_PENDING'
Exception ignored in: <function _make_registry.<locals>._Registry.__del__ at 0x7fd1f0ef5710>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 103, in __del__
  File "/data/omniverse/lib/isaac_sim-2022.2.0/kit/extscore/omni.kit.viewport.registry/omni/kit/viewport/registry/registry.py", line 98, in destroy
TypeError: 'NoneType' object is not callable
Exception ignored in: <function RegisteredActions.__del__ at 0x7fc54b1c5ef0>
Traceback (most recent call last):
  File "/data/omniverse/lib/isaac_sim-2022.2.0/extscache/omni.kit.viewport.menubar.lighting-104.0.8/omni/kit/viewport/menubar/lighting/actions.py", line 345, in __del__
  File "/data/omniverse/lib/isaac_sim-2022.2.0/extscache/omni.kit.viewport.menubar.lighting-104.0.8/omni/kit/viewport/menubar/lighting/actions.py", line 350, in destroy
TypeError: 'NoneType' object is not callable

```

**Comment by ChengshuLi** [comment]
I will need to look into this a bit more. Meanwhile, could you set `ENABLE_FLATCACHE` to be False for now?
