### ISSUE TITLE
Robot control causes crash after new objects added during slicing

### ISSUE THREAD

**Issue by cgokmen** [StanfordVL/OmniGibson#277]
To test, checkout 91c2360bf4ecb08dc29e6c355c4efe9f083f0096 and run `python .\tests\test_symbolic_primitives.py` 

After the half objects are loaded, the dynamic control API of the robot no longer works:

```
Grasping knife
Cutting steak
[INFO] [omnigibson.objects.object_base] Loaded half_apple_0 at /World/half_apple_0
[INFO] [omnigibson.objects.object_base] Loaded half_apple_1 at /World/half_apple_1
2023-09-21 21:35:26 [173,941ms] [Error] [omni.isaac.dynamic_control.plugin] Failed to refresh articulation /World/robot0/base_link
2023-09-21 21:35:26 [174,014ms] [Error] [omni.isaac.dynamic_control.plugin] Failed to refresh articulation /World/robot0/base_link
[WARNING] [omnigibson.utils.registry_utils] Object 'half_apple_0' is not in the state dict to load from. Skip loading its state.
[WARNING] [omnigibson.utils.registry_utils] Object 'half_apple_1' is not in the state dict to load from. Skip loading its state.
Traceback (most recent call last):
  File ".\tests\test_symbolic_primitives.py", line 238, in <module>
    main()
  File ".\tests\test_symbolic_primitives.py", line 231, in main
    test_cut(env, prim_gen, steak, knife, countertop)
  File ".\tests\test_symbolic_primitives.py", line 204, in test_cut
    for action in prim_gen.apply_ref(SymbolicSemanticActionPrimitiveSet.CUT, steak):
  File "C:\Users\cgokmen\OmniGibson\omnigibson\action_primitives\symbolic_semantic_action_primitives.py", line 204, in apply_ref
    yield from self._settle_robot()
  File "C:\Users\cgokmen\OmniGibson\omnigibson\action_primitives\symbolic_semantic_action_primitives.py", line 970, in _settle_robot
    yield from [self._empty_action() for _ in range(100)]
  File "C:\Users\cgokmen\OmniGibson\omnigibson\action_primitives\symbolic_semantic_action_primitives.py", line 970, in <listcomp>
    yield from [self._empty_action() for _ in range(100)]
  File "C:\Users\cgokmen\OmniGibson\omnigibson\action_primitives\symbolic_semantic_action_primitives.py", line 720, in _empty_action
    action[action_idx] = self.robot.get_joint_positions()[joint_idx]
  File "C:\Users\cgokmen\OmniGibson\omnigibson\prims\entity_prim.py", line 810, in get_joint_positions
    joint_positions = self._dc.get_articulation_dof_states(self._handle, _dynamic_control.STATE_POS)["pos"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by cgokmen** [comment]
This was fixed in #279
