### ISSUE TITLE
AttributeError: module 'gym.spaces' has no attribute 'Sequence'

### ISSUE THREAD

**Issue by KhaledSharif** [StanfordVL/OmniGibson#720]
```
Traceback (most recent call last):
  File "/home/khaled/miniconda3/envs/omnigibson/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/khaled/miniconda3/envs/omnigibson/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/examples/scenes/scene_selector.py", line 81, in <module>
    main()
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/examples/scenes/scene_selector.py", line 58, in main
    env = og.Environment(configs=cfg)
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/utils/python_utils.py", line 90, in wrapper
    func(*values.args, **values.kwargs)
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/envs/env_base.py", line 77, in __init__
    self.load()
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/envs/env_base.py", line 371, in load
    self._load_robots()
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/envs/env_base.py", line 241, in _load_robots
    og.sim.play()
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/simulator.py", line 730, in play
    self._non_physics_step()
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/simulator.py", line 639, in _non_physics_step
    obj.initialize()
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/prims/prim_base.py", line 74, in initialize
    self._initialize()
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/robots/robot_base.py", line 193, in _initialize
    self.load_observation_space()
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/utils/gym_utils.py", line 129, in load_observation_space
    self.observation_space = gym.spaces.Dict(self._load_observation_space())
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/robots/robot_base.py", line 354, in _load_observation_space
    obs_space[sensor_name] = sensor.load_observation_space()
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/utils/gym_utils.py", line 129, in load_observation_space
    self.observation_space = gym.spaces.Dict(self._load_observation_space())
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/sensors/sensor_base.py", line 100, in _load_observation_space
    for modality, space in self._obs_space_mapping.items():
  File "/home/khaled/Documents/GitHub/OmniGibson/omnigibson/sensors/vision_sensor.py", line 653, in _obs_space_mapping
    bbox_3d_space = gym.spaces.Sequence(space=gym.spaces.Tuple((
AttributeError: module 'gym.spaces' has no attribute 'Sequence'
```

How to reproduce:

```
python -m omnigibson.examples.scenes.scene_selector
```

**Comment by KhaledSharif** [comment]
Fixed by upgrading gym to latest

```
pip install gym==0.26.2
```
