### ISSUE TITLE
ValueError: Failed to execute environment step 2 in episode 1

### ISSUE THREAD

**Issue by arnavbalaji** [StanfordVL/OmniGibson#747]
Hello!

I'm trying to use the StarterSemanticAction primitives IK controller to move the Tiago Robot, and I'm using this general code to execute actions.

```
env = og.Environment(configs=cfg)
robot = env.robots[0]

controller = StarterSemanticActionPrimitives(env)
actions = controller._move_hand_direct_ik([target_pos, target_orn], ignore_failure=True, in_world_frame=False)
    for action in actions:
        env.step(action)
```

Sometimes, `env.step(action)` works without any issues, however sometimes I get this error:

```
Traceback (most recent call last):
  File "/code/omnigibson/envs/env_base.py", line 518, in step
    obs, obs_info = self.get_obs()
  File "/code/omnigibson/envs/env_base.py", line 435, in get_obs
    obs[robot.name], info[robot.name] = robot.get_obs()
  File "/code/omnigibson/robots/robot_base.py", line 304, in get_obs
    obs_dict[sensor_name], info_dict[sensor_name] = sensor.get_obs()
  File "/code/omnigibson/sensors/sensor_base.py", line 76, in get_obs
    obs, info = self._get_obs()
  File "/code/omnigibson/sensors/vision_sensor.py", line 281, in _get_obs
    obs[modality], info[modality] = self._remap_instance_segmentation(
  File "/code/omnigibson/sensors/vision_sensor.py", line 394, in _remap_instance_segmentation
    return remapper.remap(replicator_mapping, registry, img)
  File "/code/omnigibson/utils/vision_utils.py", line 111, in remap
    assert new_key is not None, f"Could not find a new key for label {label} in new_mapping!"
AssertionError: Could not find a new key for label unlabelled in new_mapping!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/omnigibson/trial/tiago_env.py", line 87, in <module>
    main()
  File "/code/omnigibson/trial/tiago_env.py", line 73, in main
    env.step(action)
  File "/code/omnigibson/envs/env_base.py", line 539, in step
    raise ValueError(f"Failed to execute environment step {self._current_step} in episode {self._current_episode}")
ValueError: Failed to execute environment step 2 in episode 1
```

I was just wondering if anyone has had any experience with this, and if I could get some guidance on what this means/how to fix it. Thanks!

**Comment by cgokmen** [comment]
Apologies for the delayed response. This issue should currently be corrected on the og-develop branch and will be included in the next release. I do recommend just waiting for the release instead of switching to the development branch however since the development branch expects Isaac Sim 4.0.0.
