### ISSUE TITLE
Investigate / silence material errors

### ISSUE THREAD

**Issue by cgokmen** [StanfordVL/OmniGibson#848]

**Comment by shengyin1224** [comment]
Hi，I encouter the same issue. Have you already solved this problem?

**Comment by VincentWanghh** [comment]
Hi, I also encouter this issue. Have you solved it? :)

**Comment by ChengshuLi** [comment]
These errors are safe to ignore for now. The root cause is that we need to decrypt our encrypted assets on the fly and immediately delete them afterwards to comply with their copyright. By the time you see these errors, the texture maps are already loaded into memory and ready to be used by Isaac, even though the errors indicate Isaac can't find these texture maps.

Meanwhile, we understand these errors are rather confusing and misleading for our users. We will try to get rid of these in our next release.

**Comment by cgokmen** [comment]
Concretely, this happens because even though we update all shader paths in post_load, sometimes we end up rendering objects before that, in which case they will render without a material. This gets corrected immediately after, but it spams the log stream and also adds some latency, so we should fix it still.

**Comment by STRIVESS** [comment]
hello! excuse me, today I follow the [OmniGibson](https://behavior.stanford.edu/omnigibson/getting_started/installation.html#setup) to install all the environment and download the datasets, but when I excute `python -m omnigibson.examples.robots.robot_control_example --quickstart` the command in my ubuntu 22.04 server, there are some similar errors,  I upload my terminal output log [run_example_histroy.txt](https://github.com/user-attachments/files/20888278/run_example_histroy.txt), can you give me some suggestions of solving the problem? thank you so much.


```
|---------------------------------------------------------------------------------------------|
| Driver Version: 565.57.01     | Graphics API: Vulkan
|=============================================================================================|
| GPU | Name                             | Active | LDA | GPU Memory | Vendor-ID | LUID       |
|     |                                  |        |     |            | Device-ID | UUID       |
|     |                                  |        |     |            | Bus-ID    |            |
|---------------------------------------------------------------------------------------------|
| 0   | NVIDIA GeForce RTX 4090          | Yes: 0 |     | 24810   MB | 10de      | 0          |
|     |                                  |        |     |            | 2684      | 6d366e98.. |
|     |                                  |        |     |            | 3         |            |
|---------------------------------------------------------------------------------------------|
| 1   | NVIDIA GeForce RTX 2080 Ti       |        |     | 11510   MB | 10de      | 0          |
|     |                                  |        |     |            | 1e07      | 0a7891cf.. |
|     |                                  |        |     |            | 81        |            |
|---------------------------------------------------------------------------------------------|
| 2   | NVIDIA GeForce RTX 4090          |        |     | 24810   MB | 10de      | 0          |
|     |                                  |        |     |            | 2684      | 2e12199a.. |
|     |                                  |        |     |            | 82        |            |
|=============================================================================================|
| OS: 22.04.5 LTS (Jammy Jellyfish) ubuntu, Version: 22.04.5, Kernel: 6.8.0-62-generic
| XServer Vendor: The X.Org Foundation, XServer Version: 12014000 (1.20.14.0)
| Processor: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
| Cores: 16 | Logical Cores: 32
|---------------------------------------------------------------------------------------------|
| Total Memory (MB): 257801 | Free Memory: 255687
| Total Page/Swap (MB): 8191 | Free Page/Swap: 0
|---------------------------------------------------------------------------------------------|
2025-06-23 16:24:03 [22,403ms] [Warning] [gpu.foundation.plugin] IOMMU is enabled.

```

```
2025-06-24 16:38:12 [96,509ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_base_link/Shader' parameter 'diffuse_texture': References an asset that can not be found: 'materials/oven-wuinhm-base_link-albedo.png'
2025-06-24 16:38:12 [96,509ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_base_link/Shader' parameter 'metallic_texture': References an asset that can not be found: 'materials/oven-wuinhm-base_link-metalness.png'
2025-06-24 16:38:12 [96,509ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_base_link/Shader' parameter 'normalmap_texture': References an asset that can not be found: 'materials/oven-wuinhm-base_link-normal.png'
2025-06-24 16:38:12 [96,509ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_base_link/Shader' parameter 'reflectionroughness_texture': References an asset that can not be found: 'materials/oven-wuinhm-base_link-roughness.png'
2025-06-24 16:38:12 [96,526ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_0/Shader' parameter 'normalmap_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_0-normal.png'
2025-06-24 16:38:12 [96,526ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_0/Shader' parameter 'metallic_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_0-metalness.png'
2025-06-24 16:38:12 [96,526ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_0/Shader' parameter 'diffuse_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_0-albedo.png'
2025-06-24 16:38:12 [96,526ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_0/Shader' parameter 'reflectionroughness_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_0-roughness.png'
2025-06-24 16:38:12 [96,527ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_0/Shader' parameter 'diffuse_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_0-albedo.png'
2025-06-24 16:38:12 [96,527ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_0/Shader' parameter 'metallic_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_0-metalness.png'
2025-06-24 16:38:12 [96,527ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_0/Shader' parameter 'normalmap_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_0-normal.png'
2025-06-24 16:38:12 [96,527ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_0/Shader' parameter 'reflectionroughness_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_0-roughness.png'
2025-06-24 16:38:12 [96,567ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_4/Shader' parameter 'normalmap_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_4-normal.png'
2025-06-24 16:38:12 [96,567ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_4/Shader' parameter 'metallic_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_4-metalness.png'
2025-06-24 16:38:12 [96,567ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_4/Shader' parameter 'diffuse_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_4-albedo.png'
2025-06-24 16:38:12 [96,567ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_4/Shader' parameter 'reflectionroughness_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_4-roughness.png'
2025-06-24 16:38:12 [96,567ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_4/Shader' parameter 'diffuse_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_4-albedo.png'
2025-06-24 16:38:12 [96,568ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_4/Shader' parameter 'metallic_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_4-metalness.png'
2025-06-24 16:38:12 [96,568ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_4/Shader' parameter 'normalmap_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_4-normal.png'
2025-06-24 16:38:12 [96,568ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/oven_wuinhm_0/Looks/oven_wuinhm_link_4/Shader' parameter 'reflectionroughness_texture': References an asset that can not be found: 'materials/oven-wuinhm-link_4-roughness.png'
2025-06-24 16:38:15 [99,450ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/sink_ksecxq_0/Looks/sink_ksecxq_base_link/Shader' parameter 'normalmap_texture': References an asset that can not be found: 'materials/sink-ksecxq-base_link-normal.png'
2025-06-24 16:38:15 [99,450ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/sink_ksecxq_0/Looks/sink_ksecxq_base_link/Shader' parameter 'metallic_texture': References an asset that can not be found: 'materials/sink-ksecxq-base_link-metalness.png'
2025-06-24 16:38:15 [99,450ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/sink_ksecxq_0/Looks/sink_ksecxq_base_link/Shader' parameter 'diffuse_texture': References an asset that can not be found: 'materials/sink-ksecxq-base_link-albedo.png'
2025-06-24 16:38:15 [99,450ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/sink_ksecxq_0/Looks/sink_ksecxq_base_link/Shader' parameter 'reflectionroughness_texture': References an asset that can not be found: 'materials/sink-ksecxq-base_link-roughness.png'
2025-06-24 16:38:15 [99,450ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/sink_ksecxq_0/Looks/sink_ksecxq_base_link/Shader' parameter 'diffuse_texture': References an asset that can not be found: 'materials/sink-ksecxq-base_link-albedo.png'
2025-06-24 16:38:15 [99,450ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/sink_ksecxq_0/Looks/sink_ksecxq_base_link/Shader' parameter 'metallic_texture': References an asset that can not be found: 'materials/sink-ksecxq-base_link-metalness.png'
2025-06-24 16:38:15 [99,450ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/sink_ksecxq_0/Looks/sink_ksecxq_base_link/Shader' parameter 'normalmap_texture': References an asset that can not be found: 'materials/sink-ksecxq-base_link-normal.png'
2025-06-24 16:38:15 [99,450ms] [Error] [omni.hydra] [UsdToMdl] Prim '/World/scene_0/sink_ksecxq_0/Looks/sink_ksecxq_base_link/Shader' parameter 'reflectionroughness_texture': References an asset that can not be found: 'materials/sink-ksecxq-base_link-roughness.png'
[WARNING] [omnigibson.objects.stateful_object] Ability 'particleSink' is incompatible with obj sink_ksecxq_0, because requirement ParticleRequirement was not met. Reason: Particle systems are not enabled when GPU dynamics is off.
2025-06-24 16:38:15 [99,529ms] [Warning] [omnigibson.objects.stateful_object] Ability 'particleSink' is incompatible with obj sink_ksecxq_0, because requirement ParticleRequirement was not met. Reason: Particle systems are not enabled when GPU dynamics is off.
[WARNING] [omnigibson.objects.stateful_object] Ability 'particleSource' is incompatible with obj sink_ksecxq_0, because requirement ParticleRequirement was not met. Reason: Particle systems are not enabled when GPU dynamics is off.
2025-06-24 16:38:15 [99,529ms] [Warning] [omnigibson.objects.stateful_object] Ability 'particleSource' is incompatible with obj sink_ksecxq_0, because requirement ParticleRequirement was not met. Reason: Particle systems are not enabled when GPU dynamics is off.
2025-06-24 16:38:15 [99,546ms] [Error] [omni.kit.app._impl] [py stderr]: Traceback (most recent call last):
  File "/home/zhifengwu/anaconda3/envs/omnigibson/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhifengwu/anaconda3/envs/omnigibson/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/examples/robots/robot_control_example.py", line 184, in <module>
    main(quickstart=args.quickstart)
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/examples/robots/robot_control_example.py", line 101, in main
    env = og.Environment(configs=cfg)
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/utils/python_utils.py", line 92, in wrapper
    func(*values.args, **values.kwargs)
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/envs/env_base.py", line 128, in __init__
    self.load()
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/envs/env_base.py", line 431, in load
    self._load_scene()
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/envs/env_base.py", line 257, in _load_scene
    og.sim.import_scene(self._scene)
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/simulator.py", line 718, in import_scene
    self._last_scene_edge = scene.load(
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/scenes/scene_base.py", line 459, in load
    new_scene_edge = self._load_scene_prim_with_objects(**kwargs)
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/scenes/scene_base.py", line 374, in _load_scene_prim_with_objects
    self.add_object(obj, _batched_call=True)
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/scenes/scene_base.py", line 653, in add_object
    obj.load(self)
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/objects/object_base.py", line 131, in load
    prim = super().load(scene)
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/prims/prim_base.py", line 129, in load
    self._post_load()
  File "/home/zhifengwu/deep_learning_collection/BEHAVIOR-1K/OmniGibson/omnigibson/objects/dataset_object.py", line 257, in _post_load
    assert self.category in avg_specs, f"Category {self.category} not found in average object specs!"
AssertionError: Category sink not found in average object specs!

```

![Image](https://github.com/user-attachments/assets/b04d7ed2-2fa3-4d63-86be-8b47edf062bd)
