### ISSUE TITLE
Error when running python -m omnigibson.examples.environments.behavior_env_demo

### ISSUE THREAD

**Issue by SherylSandberg** [StanfordVL/OmniGibson#926]
I am using Ubuntu 22.04 with CUDA Version: 12.3 and NVIDIA GeForce RTX 4060 Ti. I have installed Isaac Sim version 4.2.0.
When I run the command `python -m omnigibson.examples.environments.behavior_env_demo` , I encounter the following error:
`[INFO] [omnigibson] Demo /home/ariel/project/OmniGibson/omnigibson/examples/environments/behavior_env_demo.py
    ********************************************************************************
    Description:

    Generates a BEHAVIOR Task environment in an online fashion.

    It steps the environment 100 times with random actions sampled from the action space,
    using the Gym interface, resetting it 10 times.
    ********************************************************************************

Here is a list of available online object samplings:

[1] False: Use a pre-sampled cached BEHAVIOR activity scene
[2] True: Sample the BEHAVIOR activity in an online fashion

Choose a online object sampling (enter a number from 1 to 2): 1
[INFO] [omnigibson.simulator] ----- Starting OmniGibson. This will take 10-30 seconds... -----
Starting kit application with the following args:  ['/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/apps/omnigibson.kit', '--/app/tokens/exe-path=/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True', '--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=False', '--/app/fastShutdown=True', '--ext-folder', '/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/exts', '--ext-folder', '/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/apps', '--/physics/cudaDevice=0', '--portable']
Passing the following args to the base kit application:  []
[Info] [carb] Logging to file: /home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/kit/logs/Kit/Isaac-Sim/4.2/kit_20241002_104223.log
2024-10-02 02:42:23 [0ms] [Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
2024-10-02 02:42:23 [9ms] [Warning] [omni.ext.plugin] [ext: .git] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/.git' or '/home/ariel/project/OmniGibson/.git/config'
2024-10-02 02:42:23 [9ms] [Warning] [omni.ext.plugin] [ext: .github] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/.github' or '/home/ariel/project/OmniGibson/.github/config'
2024-10-02 02:42:23 [9ms] [Warning] [omni.ext.plugin] [ext: .overrides] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/.overrides' or '/home/ariel/project/OmniGibson/.overrides/config'
2024-10-02 02:42:23 [9ms] [Warning] [omni.ext.plugin] [ext: docker] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/docker' or '/home/ariel/project/OmniGibson/docker/config'
2024-10-02 02:42:23 [9ms] [Warning] [omni.ext.plugin] [ext: docs] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/docs' or '/home/ariel/project/OmniGibson/docs/config'
2024-10-02 02:42:23 [9ms] [Warning] [omni.ext.plugin] [ext: omnigibson.egg-info] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/omnigibson.egg-info' or '/home/ariel/project/OmniGibson/omnigibson.egg-info/config'
2024-10-02 02:42:23 [9ms] [Warning] [omni.ext.plugin] [ext: omnigibson] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/omnigibson' or '/home/ariel/project/OmniGibson/omnigibson/config'
2024-10-02 02:42:23 [9ms] [Warning] [omni.ext.plugin] [ext: tests] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/tests' or '/home/ariel/project/OmniGibson/tests/config'
2024-10-02 02:42:23 [9ms] [Warning] [omni.ext.plugin] [ext: scripts] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/scripts' or '/home/ariel/project/OmniGibson/scripts/config'
[0.073s] Failed to solve some dependencies locally, syncing with extension registry...
2024-10-02 02:42:23 [12ms] [Warning] [omni.ext.plugin] [ext: .github] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/.github' or '/home/ariel/project/OmniGibson/.github/config'
2024-10-02 02:42:23 [12ms] [Warning] [omni.ext.plugin] [ext: omnigibson] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/omnigibson' or '/home/ariel/project/OmniGibson/omnigibson/config'
2024-10-02 02:42:23 [12ms] [Warning] [omni.ext.plugin] [ext: scripts] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/scripts' or '/home/ariel/project/OmniGibson/scripts/config'
2024-10-02 02:42:23 [12ms] [Warning] [omni.ext.plugin] [ext: docker] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/docker' or '/home/ariel/project/OmniGibson/docker/config'
2024-10-02 02:42:23 [12ms] [Warning] [omni.ext.plugin] [ext: omnigibson.egg-info] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/omnigibson.egg-info' or '/home/ariel/project/OmniGibson/omnigibson.egg-info/config'
2024-10-02 02:42:23 [12ms] [Warning] [omni.ext.plugin] [ext: tests] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/tests' or '/home/ariel/project/OmniGibson/tests/config'
2024-10-02 02:42:23 [12ms] [Warning] [omni.ext.plugin] [ext: docs] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/docs' or '/home/ariel/project/OmniGibson/docs/config'
2024-10-02 02:42:23 [12ms] [Warning] [omni.ext.plugin] [ext: .overrides] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/.overrides' or '/home/ariel/project/OmniGibson/.overrides/config'
2024-10-02 02:42:23 [12ms] [Warning] [omni.ext.plugin] [ext: .git] Extensions config 'extension.toml' doesn't exist '/home/ariel/project/OmniGibson/.git' or '/home/ariel/project/OmniGibson/.git/config'
[0.075s] [ext: omni.kit.async_engine-0.0.1] startup
[DEBUG] [asyncio] Using selector: EpollSelector
[0.076s] [ext: omni.client-1.2.0] startup
[0.092s] [ext: omni.kit.registry.nucleus-0.0.0] startup
[INFO] [omni.kit.registry.nucleus.registry_manager] 'trusted' is not set for registry 'kit/default' in '/exts/omni.kit.registry.nucleus/registries'
[INFO] [omni.kit.registry.nucleus.registry_manager] 'trusted' is not set for registry 'kit/sdk' in '/exts/omni.kit.registry.nucleus/registries'
[INFO] [omni.kit.registry.nucleus.registry_manager] 'trusted' is not set for registry 'kit/community' in '/exts/omni.kit.registry.nucleus/registries'
2024-10-02 02:42:27 [3,650ms] [Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
        [omnigibson-2023.1.1] dependency: 'omni.kit.streamsdk.plugins' = { version='=2.5.2' } can't be satisfied. Available versions:
         - [omni.kit.streamsdk.plugins-4.5.3+106.0.0.lx64.r] (/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/extscache/omni.kit.streamsdk.plugins-4.5.3+106.0.0.lx64.r)
         - [omni.kit.streamsdk.plugins-4.5.2+106.0.0.lx64.r] (/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/extscache/omni.kit.streamsdk.plugins-4.5.2+106.0.0.lx64.r)
         - [omni.kit.streamsdk.plugins-4.4.0+106.0.0.lx64.r] (registry)
         - [omni.kit.streamsdk.plugins-3.2.1+105.2.lx64.r] (/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/extscache/omni.kit.streamsdk.plugins-3.2.1+105.2.lx64.r)
         - [omni.kit.streamsdk.plugins-2.6.2+105.1.lx64.r] (registry)
         - [omni.kit.streamsdk.plugins-2.5.1+105.1.lx64.r] (registry)
         - [omni.kit.streamsdk.plugins-2.5.0+105.1.lx64.r] (registry)
         - [omni.kit.streamsdk.plugins-2.3.7+105.1.lx64.r] (registry)
         - [omni.kit.streamsdk.plugins-2.0.3+105.0.lx64.r] (registry)
 Synced registries:
         - kit/default         : found 424 packages 
         - kit/sdk             : found 326 packages 
         - kit/community       : found 382 packages 

2024-10-02 02:42:27 [3,650ms] [Error] [omni.kit.app.plugin] Exiting app because of dependency solver failure...
Traceback (most recent call last):
  File "/home/ariel/miniconda3/envs/omnigibson/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ariel/miniconda3/envs/omnigibson/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ariel/project/OmniGibson/omnigibson/examples/environments/behavior_env_demo.py", line 58, in <module>
    main()
  File "/home/ariel/project/OmniGibson/omnigibson/examples/environments/behavior_env_demo.py", line 36, in main
    env = og.Environment(configs=cfg)
  File "/home/ariel/project/OmniGibson/omnigibson/utils/python_utils.py", line 90, in wrapper
    func(*values.args, **values.kwargs)
  File "/home/ariel/project/OmniGibson/omnigibson/envs/env_base.py", line 41, in __init__
    launch_simulator()
  File "/home/ariel/project/OmniGibson/omnigibson/simulator.py", line 174, in launch_simulator
    og.app = _launch_app()
  File "/home/ariel/project/OmniGibson/omnigibson/simulator.py", line 90, in _launch_app
    app = lazy.omni.isaac.kit.SimulationApp(config_kwargs, experience=str(kit_file_target.resolve(strict=True)))
  File "/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py", line 214, in __init__
    from .utils import create_new_stage, open_stage, set_livesync_stage
  File "/home/ariel/.local/share/ov/pkg/isaac-sim-4.2.0/exts/omni.isaac.kit/omni/isaac/kit/utils.py", line 17, in <module>
    from omni.kit.usd import layers
ModuleNotFoundError: No module named 'omni.kit.usd'`

I am not sure what is causing this error. I can run the command ./python.sh standalone_examples/api/omni.isaac.franka/follow_target_with_rmpflow.py under the path “~/.local/share/ov/pkg/isaac-sim-4.2.0” without any issues.
Any help would be greatly appreciated. Thanks!
![Screenshot from 2024-10-02 10-46-24](https://github.com/user-attachments/assets/78e27d14-d42c-4237-8b84-4cab1aed8b7c)

**Comment by hang-yin** [comment]
Hi! Thanks for reaching out. OmniGibson v1.1.0 was released yesterday, please check [here](https://github.com/StanfordVL/OmniGibson/releases/tag/v1.1.0) for our release notes and [here](https://behavior.stanford.edu/omnigibson/getting_started/installation.html) for our updated documentation on how to install (& more!) - note that this release is compatible with Isaac Sim 4.0.0 and 4.1.0 but not 4.2.0 yet. Let us know here if you run into any issues. Thanks!
